# Generated by Django 4.2.16 on 2024-10-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(help_text='Enter the directions for your recipe'),
        ),
    ]
