# Generated by Django 4.2.16 on 2024-10-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.CharField(help_text='Enter the directions for your recipe', max_length=1500),
        ),
    ]
